{% set name = "cylinter" %}
{% set version = "0.0.51" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/labsyspharm/cylinter.git
  git_tag: v0.0.51

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "
  entry_points:
    - cylinter=cylinter.cylinter:main
  noarch: python

requirements:
  build:
    - poetry
  host:
    - pip
    - python
    - poetry
  run:
    - python
    - cellcutter
    - hdbscan
    - joblib
    - magicgui
    - matplotlib
    - napari
    - numpy
    - natsort
    - numba
    - pandas
    - pyarrow
    - pyqt=6.*
    - pyyaml
    - qtpy
    - scikit-image
    - scikit-learn
    - seaborn
    - tifffile
    - umap-learn
    - zarr <3
    - svglib
    - pypdf2
    - imagecodecs  # MIBI data fails to be read without this
    - opencv

test:
  imports:
    - cylinter

about:
  home: https://labsyspharm.github.io/cylinter/
  license: MIT
  license_family: BSD
  summary: Quality Control Software for Multiplex Microscopy
