{% set name = "cylinter" %}
{% set version = "0.0.46" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/labsyspharm/cylinter.git
  git_tag: main

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "
  entry_points:
    - cylinter=cylinter.cylinter:main
    - prep=cylinter.prep:main
  noarch: python

requirements:
  host:
    - pip
    - python
  run:
    - python
    - cellcutter
    - hdbscan
    - joblib
    - magicgui
    - matplotlib=3.5
    - napari
    - natsort
    - numba
    - pandas
    - pyarrow
    - pyyaml
    - qtpy
    - scikit-image
    - scikit-learn
    - scipy
    - seaborn
    - tifffile
    - umap-learn
    - zarr

test:
  imports:
    - cylinter
    - prep

about:
  home: https://labsyspharm.github.io/cylinter/
  license: MIT
  license_family: BSD
  summary: Quality Control Software for Multiplex Microscopy
