{% set name = "cylinter" %}
{% set version = "0.0.47" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/labsyspharm/cylinter.git
  git_tag: v0.0.47

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "
  entry_points:
    - cylinter=cylinter.cylinter:main
  noarch: python

requirements:
  build:
    - poetry
  host:
    - pip
    - python
    - poetry
  run:
    - python
    - cellcutter
    - hdbscan
    - joblib
    - magicgui
    - matplotlib <3.6  # avoids segmentation faults when closing silhouette plot in clustering module
    - napari
    # - numpy <1.24 # avoids runtime errors in napari when empty polygon layer is added to viewer
    - numpy
    - natsort
    - numba
    - pandas
    - pyarrow
    - pyqt
    - pyyaml
    - qtpy
    - scikit-image
    - scikit-learn <1.3 # avoids error in FAST_METRICS = KDTree.valid_metrics + BallTree.valid_metrics + ["cosine", "arccos"]
    - scipy
    - seaborn
    - tifffile
    - umap-learn
    # - zarr <2.15  # zarr.LRUStoreCache() broken in current version, leads to blank images output from cellcutter
    - zarr
    - pydantic <2.0  # avoids AttributeError: module 'pydantic._migration' has no attribute 'ModelMetaclass'
    - svglib
    - pypdf2

test:
  imports:
    - cylinter

about:
  home: https://labsyspharm.github.io/cylinter/
  license: MIT
  license_family: BSD
  summary: Quality Control Software for Multiplex Microscopy
