{% set name = "cylinter" %}
{% set version = "0.0.46" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/labsyspharm/cylinter.git
  git_tag: 2023-07-02

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "
  entry_points:
    - cylinter=cylinter.cylinter:main
  noarch: python

requirements:
  build:
    - poetry
  host:
    - pip
    - python
    - poetry
  run:
    - python
    - cellcutter
    - hdbscan
    - joblib
    - magicgui
    - matplotlib
    - napari
    - natsort
    - numba
    - pandas
    - pyarrow
    - pyyaml
    - qtpy
    - scikit-image
    - scikit-learn<=1.3
    - scipy
    - seaborn
    - tifffile
    - umap-learn
    - zarr<=2.15
    - pydantic<=2.0

test:
  imports:
    - cylinter

about:
  home: https://labsyspharm.github.io/cylinter/
  license: MIT
  license_family: BSD
  summary: Quality Control Software for Multiplex Microscopy
