[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "CyLinter"
version = "0.0.57"
description = "CyLinter: An Interactive Image Segmentation Filter for Multiplex Microscopy"
readme = "README.md"
license = "MIT"
keywords = ["CyLinter", "multiplex microscopy", "quality control"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: End Users/Desktop",
    "Intended Audience :: Science/Research",
    "Framework :: napari",
    "License :: OSI Approved :: MIT License",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Topic :: Scientific/Engineering :: Visualization"
]
authors = ["Gregory J. Baker <gregory_baker2@hms.harvard.edu>"]
homepage = "https://github.com/labsyspharm/cylinter"

[tool.poetry.dependencies]
python = ">=3.11,<3.14"
cellcutter = "=0.2.13"  # this version is compatible with Zarr3
hdbscan = "*"
joblib = "*"
magicgui = "*"
matplotlib = "*"
napari = ">=0.9.0"  # cylinter code compatible with newer napari versions that handle scalebar metadata differently
numpy = "*"
natsort = "*"
numba = "*"
pandas = "*"
pyarrow = "*"
pyqt6 = "*"
pyqt6-qt6 = "*"  # 6.8.4 leads to frozen widget window sliders, but conda solve fails with 6.8.2
pyyaml = "*"
qtpy = "*"
scikit-image = "*"
scikit-learn = "*"
seaborn = "*"
umap-learn = "*"
zarr = ">=3"
tifffile = "*"
svglib = "*"
pypdf2 = "*"
imagecodecs = "*"  # MIBI data fails to be read without this
opencv-python = "*"

[tool.poetry.scripts]
cylinter = "cylinter.cylinter:main"