name: dockerhub

on:
  release:
    types: [published]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Remove leading v from the release tag
        id: rmv
        run: |
          sansv=$(echo ${{ github.event.release.tag_name }} | tr -d v)
          echo "::set-output name=tag::${{ github.repository }}:$sansv"
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{steps.rmv.outputs.tag}}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
        